<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:
import numpy as np

#Inputting Matrix from User

a = int(input("Enter Number Of Rows For Matrix1"))
b = int(input("Enter Number Of Columns For Matrix1"))

c = int(input("Enter Number Of Rows For Matrix2"))
d = int(input("Enter Number Of Columns For Matrix2"))

#If columns of matrix 1 and rows of Matrix 2 is not equal matrix multiplication not possible
if b!=c:
    print("Matrix Multiplication Not Possible")
else:
    #Initialize matrix
    A1 = []
    B1 = []
    print("Enter the entries rowwise for Matrix1")

    #User Input
    for i in range(a):
        row = []
        for j in range(b):
            row.append(int(input()))
        A1.append(row)
    
    #User Input
    print("Enter the entries rowwise for Matrix2")
    for i in range(c):
        row = []
        for j in range(d):
            row.append(int(input()))
        B1.append(row)
    
    C1 = np.zeros((a,d))
     
    def matrix_mul(A1, B1):
        for i in range(a):    #iterating through Rows of A1
             for j in range(d): #iterating through Column of B1
                    for k in range(c):#iterating through Rows of B1 
                         C1[i][j]+= A1[i][k]*B1[k][j]
        return(C1)
    
    C1 = matrix_mul(A1, B1)
  
    print("Product of matrix 1 and Matrix 2 is:",C1)
            
         
       
            
               


Enter Number Of Rows For Matrix13
Enter Number Of Columns For Matrix13
Enter Number Of Rows For Matrix23
Enter Number Of Columns For Matrix23
Enter the entries rowwise for Matrix1
1
3
4
2
5
7
5
9
6
Enter the entries rowwise for Matrix2
1
0
0
0
1
0
0
0
1
Product of matrix 1 and Matrix 2 is: [[1. 3. 4.]
 [2. 5. 7.]
 [5. 9. 6.]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [6]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure

A =  [0,5,27,6,13,28,100,45,10,79]
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
  
    
#Computing  Sum 
    sum = 0
    for i in range(len(A)):
        sum = sum+A[i]
    #print(sum)    
    
#Normalizing Elements Using Sum 
    d_dash =[]
        
    for j in range(len(A)):
        d_dash.append((A[j]/sum))
        
    #print(d_dash)  
    
#Computing Cumulative Normalized Sum 
   
    d_tilda = []
    d_tilda.insert(0,d_dash[0])

    for k in range(len(A)-1):
        
        d_tilda.append(d_tilda[k] + d_dash[k+1])
     
    #print(d_tilda)
    
#Uniform Random Number Generation

    u =  uniform(0.0,1.0)
    #print(u)

    number=0
    
 #Sampling

    for l in range(len(A)):
        if u<=d_tilda[l]:
            number=A[l]
            return number
        else:
            continue
   

  

def sampling_based_on_magnitude():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitude()

79
6
79
79
79
28
79
79
100
100
100
100
45
100
45
45
100
79
45
79
27
45
79
27
100
100
13
100
79
100
100
79
100
13
45
100
45
79
100
27
79
45
45
28
79
100
100
100
28
100
45
79
100
79
45
79
100
100
100
100
28
79
79
100
100
28
100
45
100
100
79
100
79
28
100
6
28
28
28
79
13
100
79
28
10
100
79
100
6
79
100
28
100
5
27
100
45
100
27


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [7]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    
    S1 = re.sub("\D","",String) #Removing 
    print(S1)
    S2 = re.sub("\d","#",S1)
    
    return(S2)


String = "#2a$#b%c%561#" #Input


replace_digits(String)

2561


'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [15]:
students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

def display_dash_board(x, y):
    
    diff = max(marks)-min(marks)
    
    # write code for computing top top 5 students
    top_5_students = {x:y for x,y in sorted(zip(x,y),key= lambda i:i[1],reverse = True)[:5]}
    
    # write code for computing top least 5 students
    
    least_5_students = {x:y for x,y in sorted(zip(x,y),key= lambda i:i[1])[:5]}
    
    # write code for computing top least 5 students
    
    students_within_25_and_75 = {x:y for x,y in sorted(zip(x,y),key= lambda i:i[1]) if y>(diff*.25) and y<(diff*.75)}
    
    return top_5_students, least_5_students, students_within_25_and_75
    

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)


print("top_5_students are {0}".format(top_5_students))
print("least_5_students are {0}".format(least_5_students))
print("Students who got marks between >25th percentile <75th percentile are {0}".format(students_within_25_and_75))

top_5_students are {'student8': 98, 'student10': 80, 'student2': 78, 'student5': 48, 'student7': 47}
least_5_students are {'student3': 12, 'student4': 14, 'student9': 35, 'student6': 43, 'student1': 45}
Students who got marks between >25th percentile <75th percentile are {'student9': 35, 'student6': 43, 'student1': 45, 'student7': 47, 'student5': 48}


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [8]:
import math

# here S is list of tuples and P is a tuple ot len=2

#List to store points
points = []

#List to store cosine_distances
cosine_distance = []

def closest_points_to_p(S, P):
    
    for x,y in S:
        
        numerator = x*P[0] + y*P[1]
        
        denominator = math.sqrt(x**2+ y**2)*math.sqrt(P[0]**2+P[1]**2)
        
        cosine_distance.append(math.acos(numerator/denominator))
        points.append(tuple((x,y)))
        
    #Stores closest distances in dictionary
    closest_points_to_p  = {points:cosine_distance for points,cosine_distance in sorted(zip(points,cosine_distance),key = lambda i:i[1])[:5]}     
    return list(closest_points_to_p) #Return list of tuple

S= [(1,2),(3,4),(-1,1),(6,-7),(0,6),(-5,-8),(-1,-1),(6,0),(1,-1)]

P= (3,-4)
points = closest_points_to_p(S, P)
print(points) #print the returned values

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [10]:
import re


def i_am_the_one(red,blue,line):
    coefficient = [] #Stores coefficients of line in list
    counter_r = 0  #Counter to count number of red points on one side of line
    counter_b = 0  #Counter to count number of blue points which is opposite side of line
    
    coefficient = re.findall(r"[\d\.\-\+]+", line) # Regular expression to extract integers,positive,negative and decimal sign
    #print(coefficient)

 #Using concept of ax+by-d>0(For Red) or ax+by-d<0(For Blue)
    for x,y in red:
            
            if float(coefficient[0])*x+float(coefficient[1])*y-float(coefficient[2])> 0:
                counter_r+=1
                
    for i,j in blue:
        
        if float(coefficient[0])*i+float(coefficient[1])*j-float(coefficient[2])< 0:
                counter_b+=1
        
    #print(counter_r)
    #print(counter_b)
    
    if counter_r == len(red) and counter_b == len(blue):
        
        return "YES"
    
    else:
        return "NO"
        
    
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [11]:
#Below Function works according to three conditions
#Condition 1: When Starting With '_'
#Condition 2: When Ending With '_'
#Condition 3: When first and last values are digits
#Note

def curve_smoothing(x, a, b):
    #When first value is'_'
    if a == -1:
        v = float(x[b])/(b+1)
        for i in range(a+1,b+1):
            x[i] = v      #Smoothing values
    #When last value is'_'        
    elif b == -1:
        v = float(x[a])/(len(x)-a)
        for i in range(a, len(x)):
            x[i] = v     #Smoothing Values
    else:
        v = (float(x[a])+float(x[b]))/(b-a+1)
        for i in range(a,b+1):
            x[i] = v
    return x

def replace(text):
    # Create List from the string
    x = text.split(",")
    # Get all the pairs of indices having digits
    y = [index for index, ele in enumerate(x) if ele!= '_']
    # Starting with _ 
    if y[0] != 0:
        y = [-1] + y
    # Ending with _ 
    if y[-1] != len(x)-1:
        y = y + [-1]    
    # looping through each pairs
    for (a, b) in zip(y[:-1], y[1:]): #
        curve_smoothing(x,a,b)          
    return x


S = [
    "_,_,_,24",
    "40,_,_,_,60",
    "80,_,_,_,_",
     "_,_,30,_,_,_,50,_,_"]

for i in S:
    print (replace(i))

[6.0, 6.0, 6.0, 6.0]
[20.0, 20.0, 20.0, 20.0, 20.0]
[16.0, 16.0, 16.0, 16.0, 16.0]
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [12]:
def compute_conditional_probabilites(F,S):
    numerator=0
    denominator=0
    for i in range(len(A)):
        if(A[i][1]==S):
            denominator+=1
            if(A[i][0]==F):
                numerator+=1
    print('P(F={}|S=={})={}/{}'.format(F, S, str(numerator), str(denominator)))
    
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

for F in ['F1', 'F2', 'F3', 'F4', 'F5']:
    for S in ['S1', 'S2', 'S3']:
        compute_conditional_probabilites(F,S)

P(F=F1|S==S1)=1/4
P(F=F1|S==S2)=1/3
P(F=F1|S==S3)=0/3
P(F=F2|S==S1)=1/4
P(F=F2|S==S2)=1/3
P(F=F2|S==S3)=1/3
P(F=F3|S==S1)=0/4
P(F=F3|S==S2)=1/3
P(F=F3|S==S3)=1/3
P(F=F4|S==S1)=1/4
P(F=F4|S==S2)=0/3
P(F=F4|S==S3)=1/3
P(F=F5|S==S1)=1/4
P(F=F5|S==S2)=0/3
P(F=F5|S==S3)=0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [13]:

def string_features(S1, S2):
    S1 = set(S1.split(" "))  #Converting String to Set

    S2 = set(S2.split(" "))

    a = S1 & S2     # And Operation -Common words between S1 and S2
    b = S1.difference(S2) #Difference Operation - Finding Words in S1 but not in S2
    c = S2.difference(S1) # Words in S2 but not in S1

    return len(a),list(b),list(c)

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"

a,b,c = string_features(S1, S2)
print(a)
print(b)
print(c)

7
['first', '5', 'F']
['S', '3', 'second']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [14]:
import math

def compute_log_loss(A):
    
    numerator = 0
    for Y,Y_score in A:
        
        numerator += Y*math.log(Y_score,10)+(1-Y)*math.log(1-Y_score,10)
    log_loss = (-numerator/len(A))
      
    return log_loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
log_loss = compute_log_loss(A)
print(log_loss)

0.42430993457031635
