In [48]:
import array
import os
import scipy.misc
import codecs
import numpy as np
from tqdm import tqdm
import pandas as pd
from sklearn.preprocessing import normalize
import joblib

In [6]:
def image_extract_asm():
    for asmfile in os.listdir('F:/asmFiles/'):
        filename = asmfile.split('.')[0]
        file = codecs.open('F:/asmFiles/' + asmfile, 'rb')
        filelength = os.path.getsize('F:/asmFiles/' + asmfile)
        width = int(filelength ** 0.5)
        print(filelength)
        rem = int(filelength / width)
    
        arr = array.array('B')
 
        arr.frombytes(file.read())
        file.close()
        reshaped_array = np.reshape(arr[:width * width], (width, width))

        reshaped_array = np.uint8(reshaped_array)
        
    
        scipy.misc.imsave('F:/asmFiles_image/' + filename + '.png',reshaped_array)

In [7]:
image_extract_asm()

58961309


C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning:     `imsave` is deprecated!
    `imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
    Use ``imageio.imwrite`` instead.


14679412
8921059
81988
1045140
3457122
17902651
5755583
1085462
87702580
37770554
5467471
230365
34287575
4449524
1059502
1232205
206205
167711
15800755
980898
10214955
77839406
6959810
13320173
96072155
15799886
137489
179334
34286071
16361174
53922215
15965928
170266
4738670
272748
22712916
177680
3567134
38495501
12153703
1110883
21918165
2626893
935311
79362974
181937
34289519
8789140
1414060
1033900
2112453
7991424
137318
69520131
960679
178009
8674052
187232
34285673
19565262
3775924
1798843
2680089
169367
24153817
167583
34221206
688131
4882610
62964382
5415574
34288188
1515803
34284921
6642904
181251
34296715
7979933
6215335
5473396
7833418
127038
128618
15714131
16298924
3399241
2258539
35725051
162245
84559256
11607104
9225214
171260
181488
146563
78307696
34283717
182127
1003392
8314755
96085447
6672120
170977
18110614
188750
85313161
16739135
7153691
14676077
8944375
11207863
67999449
974392
466257
38163819
178305
13644880
226209
171414
15001103
12416079
70808266
125219276


12852560
34286071
183300
207170
14049818
11715701
224437
180312
35863514
5518635
3991773
52207587
13332529
179400
8764513
148155
99501531
2462504
179378
181349
35127108
2544451
10896964
3819129
139119109
1332375
97468815
657830
1458164
1510798
176156
170565
34305058
92778849
51049151
38206856
782132
147076
186082
962278
9829883
2011151
17509522
977768
34303903
178776
182795
2327477
171102
272001
5334639
7702539
14676819
177352
14552578
35329539
6259531
126854
164267
109677864
34859072
8585863
228600
4349121
15222497
1286598
2545017
1815491
1425536
740080
11221403
3650488
35939030
227484
440827
273218
7395600
273554
49857441
1025514
825435
16402377
4926868
7967372
1001526
180451
4499054
31884493
163530
146362
59869926
5580447
50973068
1047266
1566098
170878
166255
1546995
1565385
181443
1368190
4691455
178177
127835
7843065
1318810
187206
172724
11650624
43720
183654
80195034
34283726
7494379
245915
829529
82528064
148450
965701
1160319
5278315
2332729
170465
5618524
181317
964934
59860

8928989
5361422
4779694
6222410
39286113
15658890
39216306
4079504
740948
170810
181698
10310532
7139452
12670409
458483
38129043
5435096
5311241
179454
12443912
17388994
18798056
226473
4129275
61276588
224366
35284918
181365
704148
60236280
1610556
4740004
169135
3219370
72898510
2646705
34843216
5279515
180740
1362685
245480
139642860
813554
11783616
101432439
147487
34834178
169580
22989498
37047
150560
35124882
8972909
1166471
524857
61688150
1068361
1455578
2364114
34785988
6187745
171496
11099018
7316646
1482050
6712686
4715281
7875375
22689901
185829
2779208
177655
81885914
4657764
52829590
64342262
185329
14826598
22994101
170319
11807934
23350988
8803380
4855848
96225637
3666133
10345341
206671
1334499
26216452
34900268
227817
146200
225452
8342224
997356
161711
1240155
21311194
146044
180384
962805
1167957
15132177
63574119
10408635
8677425
72760788
5457606
958112
177214
7677120
34277142
1829333
11515459
7952251
166290
7966003
19272030
6755050
171679
2137540
3978894
19678127

3853875
3142330
177987
103362647
35002176
126153
147048
49887971
4530405
19473242
22812546
19714286
38463391
34289575
17593501
59739464
3569699
517174
35129159
167649
2272283
7946980
188863
20203611
17078784
15609594
60805749
13091473
1342688
9050673
1810493
164600
790215
12528084
3565074
34276537
11748490
15646379
10067168
228154
23370550
38478793
5462719
61121967
1862961
181555
12131179
180773
8932491
167632
3906308
144010
170773
120837959
866562
2554070
166132
14982390
2864976
136251
16811943
169657
1803309
128546
28137872
26871847
72888988
23334809
6566604
665967
34278132
148773
226703
10087336
1285577
1452863
957809
11060852
14070256
225376
37025826
35468159
146736
4200848
1178856
1089014
8702439
460063
128623
1565829
8073272
147596
143299487
10987923
8947744
5414441
35711566
34827660
8917219
439832
3446731
1295880
1352257
35970655
148619
2515791
97721897
1141361
15102115
7526442
127071
1102972
166029
4710449
169025
4854696
188605
4573453
273320
77932349
34307313
95578187
180203
2

101195
136261
124486041
678675
181653
180941
34286075
177278
1230412
68542955
15691319
177167
57421753
966329
121057379
164299
179097
1064064
30239582
34280352
33282062
1060933
609945
2637747
4161166
84361321
7462282
176030
1124762
6029610
34285946
2544845
34294192
34226915
170291
171220
11103912
3071785
1031587
170442
4771186
128154
4576844
171550
128355
8958518
1230800
3875947
8037947
969191
1047546
1468651
179689
229305
1031651
3531307
22956940
2247297
83272157
25418461
84738916
8260419
66598
11396125
1803619
173984
180957
4837512
2784645
129381
123054
226901
8890713
6904937
1301171
170094
226830
34291838
89319068
6584367
128907
2159004
3076415
19172837
246584
5751571
13994719
8875372
148520
7966021
1314337
8999399
63309895
14098200
14200989
4914147
39111635
14191936
34278846
1002046
115855783
181087
226834
967336
4086440
4889734
88069544
228229
33788902
976274
782230
15263355
34173543
1452636
2236373
225415
2011718
34197776
11438889
17253750
1027240
34282787
988522
2775407
43694363

6489847
11643298
8256303
606236
227405
990576
34802505
180444
205261
169728
4388945
5407556
7860502
15738957
122155
34285825
8689874
2097490
171433
11778185
19705165
8077302
137082432
2644595
184114
22864895
2770068
1477329
34190160
1420319
3741020
1144611
7826580
968926
1044446
95062757
227541
963868
5125712
3839301
227704
179883
177752
34286690
2739414
111778
1018823
61033228
182374
3683457
6306698
171594
127467
9032579
98072608
845553
22808064
244130
8997018
227242
34285674
5327281
6140201
34289140
126935
102734016
3507936
179726
22903820
120019296
1347268
1328550
125233
132295418
172044
183242
29566
2347589
3194369
19683894
5414620
6808823
78945833
3789723
1414383
179219
693246
10577185
273994
1039396
1524700
4517959
166260
1025507
1457817
1081010
2088683
165575
159852
1032022
4046698
965223
227984
180831
2038011
9611141
180532
11084622
34197940
968035
1111484
224727
34214842
5109393
177339
7410030
94754914
274251
144978048
276008
6188500
3648717
127802
9096004
144137
4152854
13652

14663762
176691
5301294
3851422
219610
2495007
73694072
23844395
1508299
244750
34195003
177821
830416
34306473
4856987
968143
170277
8214063
1303318
167072
8729361
3855552
178662
126778
16878425
171072
181401
8897147
3821982
178590
137629
127038
1026401
179616
5765686
41630668
5498117
75343210
181780
963407
1277343
323805
177125
19045871
98474047
34288596
830445
1133900
176106
76175757
34285006
168598
5611600
38544512
187455
3651653
15091378
63847342
15928202
16704576
177890
13213051
8922144
15410952
1451250
20408243
14476739
23420103
128092
4833033
1972316
14902727
3865241
180036
142103344
5305756
181392
150421
1188376
4086998
164288
5297060
27240976
180694
109497496
25426673
23341033
71479599
32721096
277272
1422722
1486048
168360
42985057
5923819
1160738
6534517
227195
169493
1806975
169603
9782972
147509
2064384
7305110
168022
172156
14618968
10981881
147125
38308621
53580465
68538159
14719836
78835693
14568528
4405731
3394968
279589
204457
1865138
855544
35098222
18855189
977374


450254
34290818
144798
14765856
12737848
178704
976551
299194
34741958
13593402
180325
964622
225477
34954276
178357
61946820
38162968
148285
8558669
4474411
181017
965295
964761
178018
941543
90585447
649994
4342478
9007758
12171175
1068951
128239
964645
6749348
1471172
62840641
1092324
6621615
65399
41876639
172253
9069690
9229567
2945501
844884
170082
2224089
53708365
7775211
23577512
970782
1268256
34944910
1038694
2010466
228356
273915
34288074
75859596
965538
15265755
170337
3826965
228192
146724
967664
5362735
1821574
70228364
225556
38315900
35579867
966849
7642001
27425028
19023556
1124576
1384638
1451885
4474873
18204894
88560642
176948
94911101
43448252
34791369
3340335
6075878
963501
22278700
128937
278088
181344
2651225
4098320
6307370
36400499
34285105
176303
227351
19219452
22783721
168748
95513918
168157
38315941
960361
604032
178124
171349
34268482
7143708
3990171
6918126
3464835
11944830
1712108
20014412
1249115
2325798
8982291
34794861
17479637
1240481
88866724
13776

15286542
166160
163649
15908858
183350
34300668
17753653
225339
22872497
35270899
1940493
273027
503677
124626
9026416
1350121
12299706
1873732
20206802
11619170
101972892
17962927
62038202
181262
119470177
1377053
129729034
180815
25702718
128636
180781
271247
97230096
977643
18780235
166953
1079774
9647325
186724
169207
166553
2544638
7275044
964124
1725131
66612895
111039715
4215835
12713296
1018771
34876450
18486846
177481
1019698
679947
16733886
172760
7706332
3244409
715278
276451
352745
179206
38307655
3495454
76256013
964998
2071133
127417
148178
95978682
135810856
148803
35223178
34287503
264350
6489674
1702236
75644608
984767
35130273
970742
8895557
48901105
178525
34288427
1080340
1018912
170220
2093098
179816
664196
270552
4496332
665953
209144
176132
18381538
82289898
1904173
4038169
9276837
180408
3828450
1282038
3402117
126646
6577867
5463276
49872207
3224578
227743
34211291
64251354
1471269
13159966
739427
31632597
138462
70141572
15327686
5273680
180143
1621284
166010


37878051
834193
19427326
11477434
968584
149372
177330
16263283
34284538
10675851
32813425
34746538
4384566
8424928
1399528
34288293
147116
146372
70984520
7927504
182334
7920142
6166298
171050
11635466
3127995
5153710
968696
132707
5157995
5230254
186543
86689061
38721850
177399
10929514
35319723
1342691
34285748
28299464
35035923
675668
1468468
14364408
8559950
180640
18390318
126001900
18433743
106140445
127067
34219237
37712913
42193416
180359
177356
2495938
15067862
10547377
6846695
34277653
3975248
20354560
981110
6611523
965982
3703279
1017430
1191016
3010682
11612182
123370
4814781
1329285
1002304
61299039
171442
179531
2664809
983486
185134
1297460
178617
2207156
79085953
85462046
3394478
177835
5450042
964898
9086484
8876833
18338296
59202680
35220816
170928
184448
11473716
128422
9934354
8499522
205556
1082335
14542110
1367741
4584359
11641446
125780
3916093
8606405
5358035
1095976
125413
8993736
1157451
1349176
128317
177952
187266
148232
34287302
4438097
2182602
980886
142

227960
977463
680133
34287824
181273
3873104
8303534
1425476
1213834
127558
224025
8733810
3864864
36353846
5455739
1244105
4894493
5355898
1753591
26505063
324832
136030
13150024
225939
136699
77423744
1023472
1317506
1250186
4384684
228017
3497181
779218
184372
882317
183587
2413711
149976
1249233
7305109
3769789
1075823
10835329
1066853
192274
169667
162267
35314573
22115273
8929504
1039398
974284
1616107
4377525
8223637
272914
11254586
41580711
1465587
111931959
2594116
8845114
172054
166525
14356700
1027693
179086
181024
6679986
1316788
39482058
35093366
6077548
34284091
127468
16935940
117999209
2340911
19688670
1020752
3776618
4320927
1983257
1487386
9001694
170608
7252295
6300421
11118890
178038
1040628
3485532
1446392
1864581
38171551
962523
274949
146933
10373627
107431204
1945787
170333
11042073
34286899
162448
5146473
224340
136396
38266021
2131159
4136624
6031962
11720621
35121078
22862092
4892542
4100752
21183509
8976115
177812
4404329
170062
5250157
61016626
1024370
1801

# First 200 Image Pixels

In [37]:
import cv2
imagefeatures = np.zeros((10868, 200))

In [39]:
fnames =[]
for i, asmfile in tqdm(enumerate(os.listdir('F:/asmFiles_image/'))):
    img = cv2.imread('F:/asmFiles_image/' + asmfile.split('.')[0] + '.png')
    img_arr = img.flatten()[:200]
    imagefeatures[i, :] += img_arr


10868it [25:56,  6.98it/s]


In [40]:
np.save('imagefeatures',imagefeatures)

In [41]:
with open('imagefeatures.npy', 'rb') as f:
   imagefeatures = np.load(f)
print(imagefeatures)

[[144. 144. 144. ...  90.  90.  90.]
 [ 92.  92.  92. ...  90.  90.  90.]
 [144. 144. 144. ...  90.  90.  90.]
 ...
 [ 72.  72.  72. ...  45.  45.  45.]
 [ 72.  72.  72. ...  45.  45.  45.]
 [ 72.  72.  72. ...  45.  45.  45.]]


In [58]:
image_features_name = []
for i in tqdm(range(200)):
    image_features_name.append('pixel' + str(i))
imgdf = pd.DataFrame(normalize(imagefeatures), columns = image_features_name)


100%|████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:00<?, ?it/s]


In [59]:
imgdf.head()

pixel0    pixel1    pixel2    pixel3    pixel4    pixel5    pixel6  \
0  0.107353  0.107353  0.107353  0.102880  0.102880  0.102880  0.096916   
1  0.060808  0.060808  0.060808  0.153341  0.153341  0.153341  0.133512   
2  0.107353  0.107353  0.107353  0.102880  0.102880  0.102880  0.096916   
3  0.107571  0.107571  0.107571  0.103089  0.103089  0.103089  0.097113   
4  0.107353  0.107353  0.107353  0.102880  0.102880  0.102880  0.096916   

     pixel7    pixel8    pixel9  ...  pixel190  pixel191  pixel192  pixel193  \
0  0.096916  0.096916  0.101389  ...  0.067096  0.067096  0.067096  0.067096   
1  0.133512  0.133512  0.158629  ...  0.059486  0.059486  0.059486  0.059486   
2  0.096916  0.096916  0.101389  ...  0.067096  0.067096  0.067096  0.067096   
3  0.097113  0.097113  0.101595  ...  0.067232  0.067232  0.067232  0.067232   
4  0.096916  0.096916  0.101389  ...  0.067096  0.067096  0.067096  0.067096   

   pixel194  pixel195  pixel196  pixel197  pixel198  pixel199  
0  0.067096  0.067096  0.067096  0.067096  0.067096  0.067096  
1  0.059486  0.059486  0.059486  0.059486  0.059486  0.059486  
2  0.067096  0.067096  0.067096  0.067096  0.067096  0.067096  
3  0.067232  0.067232  0.067232  0.067232  0.067232  0.067232  
4  0.067096  0.067096  0.067096  0.067096  0.067096  0.067096  

[5 rows x 200 columns]

In [60]:
#Adding Column - ID to asm image dataframe

fnames =[]
for i, asmfile in tqdm(enumerate(os.listdir('F:/asmFiles_image/'))):
    fnames.append(asmfile.split('.')[0])

imgdf.insert(0,"ID",fnames)  

10868it [00:00, 1557458.52it/s]


In [61]:
imgdf.head()

ID    pixel0    pixel1    pixel2    pixel3    pixel4  \
0  01azqd4InC7m9JpocGv5  0.107353  0.107353  0.107353  0.102880  0.102880   
1  01IsoiSMh5gxyDYTl4CB  0.060808  0.060808  0.060808  0.153341  0.153341   
2  01jsnpXSAlgw6aPeDxrU  0.107353  0.107353  0.107353  0.102880  0.102880   
3  01kcPWA9K2BOxQeS5Rju  0.107571  0.107571  0.107571  0.103089  0.103089   
4  01SuzwMJEIXsK7A8dQbl  0.107353  0.107353  0.107353  0.102880  0.102880   

     pixel5    pixel6    pixel7    pixel8  ...  pixel190  pixel191  pixel192  \
0  0.102880  0.096916  0.096916  0.096916  ...  0.067096  0.067096  0.067096   
1  0.153341  0.133512  0.133512  0.133512  ...  0.059486  0.059486  0.059486   
2  0.102880  0.096916  0.096916  0.096916  ...  0.067096  0.067096  0.067096   
3  0.103089  0.097113  0.097113  0.097113  ...  0.067232  0.067232  0.067232   
4  0.102880  0.096916  0.096916  0.096916  ...  0.067096  0.067096  0.067096   

   pixel193  pixel194  pixel195  pixel196  pixel197  pixel198  pixel199  
0  0.067096  0.067096  0.067096  0.067096  0.067096  0.067096  0.067096  
1  0.059486  0.059486  0.059486  0.059486  0.059486  0.059486  0.059486  
2  0.067096  0.067096  0.067096  0.067096  0.067096  0.067096  0.067096  
3  0.067232  0.067232  0.067232  0.067232  0.067232  0.067232  0.067232  
4  0.067096  0.067096  0.067096  0.067096  0.067096  0.067096  0.067096  

[5 rows x 201 columns]

In [62]:
joblib.dump(imgdf, 'imgdf')

['imgdf']

In [63]:
imgdf=joblib.load('imgdf')

In [64]:
imgdf.head()

ID    pixel0    pixel1    pixel2    pixel3    pixel4  \
0  01azqd4InC7m9JpocGv5  0.107353  0.107353  0.107353  0.102880  0.102880   
1  01IsoiSMh5gxyDYTl4CB  0.060808  0.060808  0.060808  0.153341  0.153341   
2  01jsnpXSAlgw6aPeDxrU  0.107353  0.107353  0.107353  0.102880  0.102880   
3  01kcPWA9K2BOxQeS5Rju  0.107571  0.107571  0.107571  0.103089  0.103089   
4  01SuzwMJEIXsK7A8dQbl  0.107353  0.107353  0.107353  0.102880  0.102880   

     pixel5    pixel6    pixel7    pixel8  ...  pixel190  pixel191  pixel192  \
0  0.102880  0.096916  0.096916  0.096916  ...  0.067096  0.067096  0.067096   
1  0.153341  0.133512  0.133512  0.133512  ...  0.059486  0.059486  0.059486   
2  0.102880  0.096916  0.096916  0.096916  ...  0.067096  0.067096  0.067096   
3  0.103089  0.097113  0.097113  0.097113  ...  0.067232  0.067232  0.067232   
4  0.102880  0.096916  0.096916  0.096916  ...  0.067096  0.067096  0.067096   

   pixel193  pixel194  pixel195  pixel196  pixel197  pixel198  pixel199  
0  0.067096  0.067096  0.067096  0.067096  0.067096  0.067096  0.067096  
1  0.059486  0.059486  0.059486  0.059486  0.059486  0.059486  0.059486  
2  0.067096  0.067096  0.067096  0.067096  0.067096  0.067096  0.067096  
3  0.067232  0.067232  0.067232  0.067232  0.067232  0.067232  0.067232  
4  0.067096  0.067096  0.067096  0.067096  0.067096  0.067096  0.067096  

[5 rows x 201 columns]